### ISSUE TITLE
Error: require.paths is removed.

### ISSUE THREAD

**Issue by atian25** [xcambar/n-ext#2]
E:\Workspace\Code\PureReader>node app.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH envi
ronment variable instead.
    at Function.<anonymous> (module.js:378:11)
    at [object Object].bootstrapCore (E:\Workspace\Code\PureReader\node_modules\
n-ext\index.js:67:17)
    at Object.<anonymous> (E:\Workspace\Code\PureReader\app.js:31:18)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)

**Comment by xcambar** [comment]
Right.
N-ext needs an update regarding the changes in Node's _require_ implementation. (NodeJS >=0.6)

Will investigate in the next few days.

Thx for the report.

**Comment by atian25** [comment]
btw, ext can be update to 4.1rc1

**Comment by xcambar** [comment]
I only intend to update Ext to a further stable version. 4.1rc1 is, as it is named, a release candidate.
As stable as it may be, I recommend you wait for the final 4.1.
